;;; ~/.config/doom/packages.el

(package! apache-mode)
(package! company-phpactor)
(package! confluence)
(package! mu4e-alert)
(package! nginx-mode)
(package! org-jira)
(package! org-pomodoro)
(package! org-super-agenda)
(package! ox-slack)
(package! ox-twbs)
(package! phpactor)
(package! slack)
(package! speed-type)
(package! uuidgen)
