music_directory "/home/tonya/Music/Tony"
playlist_directory "/home/tonya/Music/Tony"
db_file "/home/tonya/.mpd/mpd.db"
log_file "/home/tonya/.mpd/mpd.log"
pid_file "/home/tonya/.mpd/mpd.pid"
state_file "/home/tonya/.mpd/mpdstate"

audio_output {
	type "pulse"
	name "pulse audio"
}

audio_output {
    type                    "fifo"
    name                    "my_fifo"
    path                    "/tmp/mpd.fifo"
    format                  "44100:16:2"
}

bind_to_address "127.0.0.1"
port "6600"

follow_outside_symlinks     "yes"
follow_inside_symlinks      "yes"