[colors]
;background = ${xrdb:color0:#222}
background = #222
background-alt = #444
;foreground = ${xrdb:color7:#222}
foreground = #dfdfdf
foreground-alt = #ccc
primary = #267fb5
secondary = #748aa6
alert = #FF410D
success = #0f0

