[colors]
;background = ${xrdb:color0:#222}
background = #ffffff
background-alt = #5c6370
;foreground = ${xrdb:color7:#222}
foreground = #282c34
foreground-alt = #282c34
primary = #61afef
secondary = #d19a66
alert = #e06c75
success = #0f0

