[colors]
;background = ${xrdb:color0:#222}
;foreground = ${xrdb:color7:#222}
background = #1d1f21
background-alt = #5c6370
foreground = #c5c8c6
foreground-alt = #c5c8c6
primary = #61afef
secondary = #d19a66
alert = #e06c75
success = #0f0

