;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;==========================================================

[module/launcher]
type = custom/text
content = 

content-background = ${color.shade1}
content-foreground = ${color.modulefg}
content-padding = 1

click-left = rofi -show run -fullscreen True -lines 5 -line-margin 5 -padding 300 -bw 0

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/title]
type = internal/xwindow

format = <label>
format-background = ${color.shade2}
format-foreground = ${color.modulefg}
format-padding = 1

label = %title%
label-maxlen = 80

;;label-empty = Arch Linux
;;label-empty-foreground = #707880

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/alsa]
type = internal/alsa

format-volume = <ramp-volume> <label-volume>
format-volume-background = ${color.shade3}
format-volume-foreground = ${color.modulefg}
format-volume-padding = 1

label-volume = %percentage%%

format-muted-prefix = 
label-muted = " Muted"
format-muted-background = ${color.shade3}
format-muted-foreground = ${color.modulefg}
format-muted-padding = 1

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
ramp-volume-3 = 
ramp-volume-4 = 

[module/pavolume]
type = custom/script
tail = true
label = %output%
exec = ~/.config/polybar/scripts/pavolume.sh --listen
click-right = exec pavucontrol
click-left = ~/.config/polybar/scripts/pavolume.sh --togmute
scroll-up = ~/.config/polybar/scripts/pavolume.sh --up
scroll-down = ~/.config/polybar/scripts/pavolume.sh --down
format-background = ${color.shade3}
format-foreground = ${color.modulefg}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/backlight]
type = internal/xbacklight

card = intel_backlight

format = <ramp> <label>
format-background = ${color.shade4}
format-foreground = ${color.modulefg}
format-padding = 1

label = %percentage%%

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-3 = 
ramp-4 = 

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/battery]
type = internal/battery

full-at = 99

battery = BAT1
adapter = ACAD

poll-interval = 2
time-format = %H:%M

format-charging = <animation-charging> <label-charging>
format-charging-background = ${color.shade5}
format-charging-foreground = ${color.modulefg}
format-charging-padding = 1

format-discharging = <ramp-capacity> <label-discharging>
format-discharging-background = ${color.shade5}
format-discharging-foreground = ${color.modulefg}
format-discharging-padding = 1

label-charging = %percentage%%
label-discharging = %percentage%%

label-full = Fully Charged
label-full-background = ${color.shade5}
label-full-foreground = ${color.modulefg}
label-full-padding = 1

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-5 = 
ramp-capacity-6 = 
ramp-capacity-7 = 
ramp-capacity-8 = 
ramp-capacity-9 = 

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-5 = 
animation-charging-6 = 
animation-charging-7 = 
animation-charging-8 = 
animation-charging-framerate = 750

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/date]
type = internal/date
interval = 1.0
date = " %a %b %d, %Y"
date-alt = " %a %b %d, %Y"
time = %l:%M%p
time-alt = %l:%M%p
format-prefix = " "
format-background = ${color.shade2}
format-foreground = ${color.modulefg}
label = "%date% %time% "

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/powermenu]
type = custom/menu

expand-right = true

menu-0-0 = reboot
menu-0-0-exec = menu-open-1
menu-0-1 = shutdown
menu-0-1-exec = menu-open-2

menu-1-0 = back
menu-1-0-exec = menu-open-0
menu-1-1 = reboot
menu-1-1-exec = systemctl reboot

menu-2-0 = shutdown
menu-2-0-exec = systemctl poweroff
menu-2-1 = back
menu-2-1-exec = menu-open-0

format-spacing = 1 
format-background = ${color.shade1}
format-foreground = ${color.modulefg}
format-padding = 1

label-open = 
label-close = 
label-separator = |

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/network]
type = internal/network
interface = enp8s0

interval = 1.0
accumulate-stats = true
unknown-as-up = true

format-connected = <ramp-signal> <label-connected>
format-connected-background = ${color.shade3}
format-connected-foreground = ${color.modulefg}
format-connected-padding = 1

format-disconnected = <label-disconnected>
format-disconnected-background = ${color.shade3}
format-disconnected-foreground = ${color.modulefg}
format-disconnected-padding = 1

label-connected = "%essid%"
label-disconnected =  "Not Connected"
ramp-signal-0 = 
ramp-signal-1 = 
ramp-signal-2 = 
ramp-signal-3 = 
ramp-signal-4 = 

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/colors]
type = custom/text
content = 
content-background = ${color.shade7}
content-foreground = ${color.modulefg}
content-padding = 1

click-left = ~/.config/polybar/scripts/color-switch.sh &
click-right = ~/.config/polybar/scripts/type-switch.sh &

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/cpu]
type = internal/cpu
interval = 1

format-background = ${color.shade5}
format-foreground = ${color.modulefg}
format-prefix = "  "


label-font = 1

; Available tags:
;   <label> (default)
;   <bar-load>
;   <ramp-load>
;   <ramp-coreload>
format = <label>


; Available tokens:
;   %percentage% (default) - total cpu load
;   %percentage-cores% - load percentage for each core
;   %percentage-core[1-9]% - load percentage for specific core
label = "Cpu %percentage:3%%  "

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/memory]
type = internal/memory
interval = 1
; Available tokens:
;   %percentage_used% 
;   %percentage_free%
;   %gb_used% (default)
;   %gb_free%
;   %gb_total%
;   %mb_used%
;   %mb_free%
;   %mb_total%
label = %gb_used%

format = "Mem <label>  "
format-prefix = "   "
format-prefix-foreground = ${color.modulefg}
format-background = ${color.shade4}
format-foreground = ${color.modulefg}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/networkspeedup]
type = internal/network
;interface = wlp3s0
;interface = enp14s0
;interface = enp0s31f6
interface = enp8s0
label-connected = "%upspeed:7%  "
format-connected = <label-connected>
format-connected-prefix = "  "
format-connected-prefix-foreground = ${color.modulefg}
format-connected-foreground = ${color.modulefg}
format-connected-background = ${color.shade7}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/networkspeeddown]
type = internal/network
;interface = wlp3s0
;interface = enp14s0
;interface = enp0s31f6
interface = enp8s0
label-connected = "%downspeed:7%  "
format-connected = <label-connected>
format-connected-prefix = "  "
format-connected-prefix-foreground = ${color.modulefg}
format-connected-foreground = ${color.modulefg}
format-connected-background = ${color.shade6}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/spotify]
type = custom/script
exec = python ~/.config/polybar/scripts/spotify.py  -f '{song} - {artist} - {album}'
interval = 1

;format = <label>
format-foreground = ${color.modulefg}
format-background = ${color.shade1}

format-padding = 2
; format-underline = #0f0
format-prefix = "  "
format-prefix-foreground = ${color.modulefg}
label = %output:0:150%

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/temperature]
type = internal/temperature
; Thermal zone to use
; To list all the zone types, run
; $ for i in /sys/class/thermal/thermal_zone*; do echo "$i: $(<$i/type)"; done
; Default: 0
thermal-zone = 0

; Full path of temperature sysfs path
; Use `sensors` to find preferred temperature source, then run
; $ for i in /sys/class/hwmon/hwmon*/temp*_input; do echo "$(<$(dirname $i)/name): $(cat ${i%_*}_label 2>/dev/null || echo $(basename ${i%_*})) $(readlink -f $i)"; done
; to find path to desired file
; Default reverts to thermal zone setting
hwmon-path = /sys/devices/platform/coretemp.0/hwmon/hwmon1/temp1_input

warn-temperature = 70
format = <ramp> <label>
format-background = ${color.shade6}
format-foreground = ${color.shade6}
format-warn = <ramp> <label-warn>
label = "%temperature% "
label-warn = " %temperature% "
label-warn-foreground = ${color.shade6}

ramp-0 = " "
ramp-1 = " "
ramp-2 = " "
ramp-3 = " "
ramp-4 = " "
ramp-foreground =${color.modulefg}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/xkeyboard]
;https://github.com/jaagr/polybar/wiki/Module:-xkeyboard
type = internal/xkeyboard
blacklist-0 = num lock

format-prefix = " "
format-prefix-foreground = ${color.modulefg}
format-prefix-background = ${color.shade7}
format-prefix-underline = #3ecfb2
format-foreground = ${color.modulefg}
format-background = ${color.shade7}

label-layout = %layout%
label-layout-underline = #3ecfb2
label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-background = ${color.modulefg}
label-indicator-underline = ${color.shade7}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/filesystem]
type = internal/fs

; Mountpoints to display
mount-0 = /
;mount-1 = /home
;mount-2 = /var

; Seconds to sleep between updates
; Default: 30
interval = 30

; Display fixed precision values
; Default: false
fixed-values = false

; Spacing between entries
; Default: 2
spacing = 4

; Available tags:
;   <label-mounted> (default)
;   <bar-free>
;   <bar-used>
;   <ramp-capacity>
format-mounted = <label-mounted>
format-mounted-foreground = ${color.modulefg}
format-mounted-background = ${color.shade1}


; Available tokens:
;   %mountpoint%
;   %type%
;   %fsname%
;   %percentage_free%
;   %percentage_used%
;   %total%
;   %free%
;   %used%
; Default: %mountpoint% %percentage_free%%
label-mounted = %mountpoint% : %used% used of %total%

; Available tokens:
;   %mountpoint%
; Default: %mountpoint% is not mounted
label-unmounted = %mountpoint% not mounted
format-unmounted-foreground = ${color.modulefg}
format-unmounted-background = ${color.shade1}
;format-unmounted-underline = ${colors.alert}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/mpd]
type = internal/mpd
;format-online =  "<label-song>   <icon-prev>  <icon-stop>  <toggle>  <icon-next>"
format-online =  "<label-song>  <bar-progress>"
;format-online =  "<label-song>  <bar-progress> <icon-prev>  <icon-stop>  <toggle>  <icon-next>"
icon-prev = 
icon-stop = 
icon-play = 
icon-pause = 
icon-next = 
label-song-maxlen = 40
label-song-ellipsis = true
bar-progress-width = 10
bar-progress-indicator = 
bar-progress-fill = 
bar-progress-empty = 
bar-progress-fill-foreground = #ff0
bar-progress-fill-background = ${color.modulefg}
bar-progress-indicator-foreground = ${color.shade2}
format-online-foreground = ${color.shade2}
format-online-background = ${color.modulefg}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/pub-ip]
type = custom/script
exec = ~/.config/polybar/scripts/pub-ip.sh
interval = 100
format-foreground = ${color.modulefg}
format-background = ${color.shade5}
label = %output%
format-prefix = "  "
format-prefix-foreground = ${color.modulefg}
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/uptime]
type = custom/script
exec = uptime | awk -F, '{sub(".*up ",x,$1);print $1}'
interval = 100
label = Uptime : %output%

format-foreground = ${color.modulefg}
format-background = ${color.shade2}
format-prefix = " "
format-prefix-foreground = ${color.modulefg}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/wireless-network]
;https://github.com/jaagr/polybar/wiki/Module:-network
type = internal/network
interface = ${env:WIRELESS}
interval = 3.0
label-connected = %essid%

format-connected = <label-connected>
;format-connected = <ramp-signal> <label-connected>
format-connected-foreground = ${colors.foreground}
format-connected-background = ${colors.background}
format-connected-prefix = "  "
format-connected-prefix-foreground = #7e52c6
format-connected-prefix-background = ${colors.background}
format-connected-underline = #7e52c6

label-disconnected = %ifname% disconnected
label-disconnected-foreground = ${colors.alert}
label-disconnected-background = ${colors.background}

format-disconnected = <label-disconnected>
format-disconnected-foreground = ${colors.alert}
format-disconnected-background = ${colors.background}
format-disconnected-prefix = "  "
format-disconnected-prefix-foreground = ${colors.alert}
format-disconnected-prefix-background = ${colors.background}
format-disconnected-underline =${colors.alert}

ramp-signal-0 = ▁
ramp-signal-1 = ▂
ramp-signal-2 = ▃
ramp-signal-3 = ▄
ramp-signal-4 = ▅
ramp-signal-5 = ▆
ramp-signal-6 = ▇
ramp-signal-7 = █
ramp-signal-foreground = #7e52c6

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/workspaces]
type = internal/xworkspaces

pin-workspaces = false
enable-click = true
enable-scroll = true

label-active = 
label-occupied = 
label-urgent = 
label-empty = 

format = <label-state>

label-monitor = %name%
label-active-foreground = ${color.accent}
label-occupied-foreground = ${color.yellow}
label-urgent-foreground = ${color.red}
label-empty-foreground = ${color.modulefg-alt}

label-active-padding = 1
label-urgent-padding = 1
label-occupied-padding = 1
label-empty-padding = 1

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/ewmh]
type = internal/xworkspaces

pin-workspaces = true
enable-click = true
enable-scroll = true
reverse-scroll = true

;extra icons to choose from
;http://fontawesome.io/cheatsheet/
;       v     

icon-0 = "0:Spotify;"
icon-1 = "1:Emacs;"
icon-2 = "1:Browser;"
icon-3 = ""
icon-4 = ""
icon-5 = ""
icon-6 = ""
icon-7 = ""
icon-8 = ""
icon-9 = ""
icon-default = ""
format = <label-state>
label-monitor = %icon%

label-active = %icon%
label-active-foreground = ${color.modulefg}
label-active-background = ${color.shade1}
label-active-underline= ${color.shade1}
label-active-padding = 1

label-occupied = %icon%
label-occupied-background = ${color.shade6}
label-occupied-padding = 1

label-urgent = %icon%
label-urgent-foreground = ${color.modulefg}
label-urgent-background = ${color.shade1}
label-urgent-underline = ${color.shade1}
label-urgent-padding = 1

label-empty = %icon%
label-empty-foreground = ${color.shade1}
label-empty-padding = 1
format-foreground = ${color.shade7}
format-background = ${color.modulefg}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/bspwm]
type = internal/bspwm
pin-workspaces = true
inline-mode = false
enable-click = true
enable-scroll = true
reverse-scroll = true
fuzzy-match = true

ws-icon-[0-9]+ = <label>;<icon>
; Note that the <label> needs to correspond with the bspwm workspace name
; Neither <label> nor <icon> can contain a semicolon (;)
ws-icon-0 = 1; 
ws-icon-1 = 2;
ws-icon-2 = 3;
ws-icon-3 = 4;
ws-icon-4 = 5;
ws-icon-5 = 6;
ws-icon-6 = 7;
ws-icon-7 = 8;
ws-icon-8 = 9;
ws-icon-9 = 0;
ws-icon-default =""

; Available tags:
;   <label-monitor>
;   <label-state> - gets replaced with <label-(focused|urgent|occupied|empty)>
;   <label-mode> - gets replaced with <label-(monocle|tiled|fullscreen|floating|locked|sticky|private)>
; Default: <label-state>
format = <label-state> <label-mode>

label-monitor = %name%

label-dimmed-foreground = ${color.shade1}
label-dimmed-focused-background = ${color.shade1}

label-focused = %icon%
label-focused-foreground = ${color.modulefg}
label-focused-background = ${color.shade1}
label-focused-padding = 2
label-focused-underline= #FFFFFF	


label-occupied = %icon%
label-occupied-foreground= ${color.modulefg}
label-occupied-background = ${color.shade5}
label-occupied-padding = 2
label-occupied-underline= ${color.shade1}


label-urgent = %icon%
label-urgent-foreground = ${color.modulefg}
label-urgent-background = ${color.modulefg}

label-empty = %icon%
label-empty-foreground = ${color.shade7}
label-empty-background = ${color.bground}
label-empty-padding = 2

; The following labels will be used to indicate the layout/mode
; for the focused workspace. Requires <label-mode>
;
; Available tokens:
;   None
;label-monocle = 
;label-tiled = 
;label-fullscreen = 
;label-floating = 
;label-pseudotiled = P
;label-locked = 
;label-locked-foreground = #bd2c40
;label-sticky = 
;label-sticky-foreground = #fba922
;label-private = 
;label-private-foreground = #bd2c40
;label-marked = M

; Separator in between workspaces
; label-separator = |
; label-separator-padding = 2
; label-separator-foreground = ${color.shade1}

; format-foreground = ${color.modulefg}
; format-background = ${color.shade6}
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;	    __________  ______
;;	   / ____/ __ \/ ____/
;;	  / __/ / / / / /_    
;;	 / /___/ /_/ / __/    
;;	/_____/\____/_/       
;;
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
