[module/xwindow]
type = internal/xwindow
label = %title:0:30:...%

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}
format-prefix-underline = ${colors.secondary}

label-layout = %layout%
label-layout-underline = ${colors.secondary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-background = ${colors.secondary}
label-indicator-underline = ${colors.secondary}

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = %{F#267fb5}%mountpoint%%{F-}: %percentage_used%%
label-unmounted = %mountpoint% not mounted

[module/backlight]
type = internal/backlight
card = intel_backlight

format = <bar> <label>
format-prefix = " "

bar-width = 10
bar-indicator = |
bar-indicator-foreground = #ff
bar-indicator-font = 2
bar-fill = ─
bar-fill-font = 2
bar-fill-foreground = ${colors.alert}
bar-empty = ─
bar-empty-font = 2
bar-empty-foreground = ${colors.foreground-alt}

[module/backlight-acpi]
inherit = module/backlight
type = internal/backlight
card = intel_backlight

[module/wlan]
type = internal/network
interface = wlp2s0
interval = 3.0

format-connected = <ramp-signal> <label-connected>
format-connected-underline = ${colors.primary}
label-connected = %essid%

format-disconnected =
;format-disconnected = <label-disconnected>
;format-disconnected-underline = ${self.format-connected-underline}
;label-disconnected = %ifname% disconnected
;label-disconnected-foreground = ${colors.foreground-alt}

ramp-signal-0 = 
ramp-signal-1 = 
ramp-signal-2 = 
ramp-signal-3 = 
ramp-signal-4 = 
ramp-signal-foreground = ${colors.foreground-alt}

[module/eth]
type = internal/network
interface = enp3s0
interval = 3.0

format-connected-underline = ${colors.primary}
format-connected-prefix = " "
format-connected-prefix-foreground = ${colors.foreground-alt}
label-connected = %local_ip%

format-disconnected =
;format-disconnected = <label-disconnected>
;format-disconnected-underline = ${self.format-connected-underline}
;label-disconnected = %ifname% disconnected
;label-disconnected-foreground = ${colors.foreground-alt}

[module/volume]
type = internal/volume

format-volume = <bar-volume> <label-volume>
label-volume-foreground = ${root.foreground}

format-volume-prefix = " "

format-muted-prefix = " "
format-muted-foreground = ${colors.foreground-alt}
label-muted = sound muted

bar-volume-width = 10
bar-volume-foreground-0 = ${colors.primary}
bar-volume-foreground-1 = ${colors.primary}
bar-volume-foreground-2 = ${colors.primary}
bar-volume-foreground-3 = ${colors.primary}
bar-volume-foreground-4 = ${colors.primary}
bar-volume-foreground-5 = ${colors.alert}
bar-volume-foreground-6 = ${colors.alert}
bar-volume-gradient = false
bar-volume-indicator = |
bar-volume-indicator-font = 2
bar-volume-fill = ─
bar-volume-fill-font = 2
bar-volume-empty = ─
bar-volume-empty-font = 2
bar-volume-empty-foreground = ${colors.foreground-alt}


[module/temperature]
type = internal/temperature
thermal-zone = 0
warn-temperature = 60

format = <ramp> <label>
format-underline = ${colors.secondary}
format-warn = <ramp> <label-warn>
format-warn-underline = ${self.format-underline}

label = %temperature%
label-warn = %temperature%
label-warn-foreground = ${colors.secondary}

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-foreground = ${colors.foreground-alt}

[module/powermenu]
type = custom/menu

format-spacing = 1

label-open = 
label-open-foreground = ${colors.primary}
label-close =  cancel
label-close-foreground = ${colors.primary}
label-separator = |
label-separator-foreground = ${colors.foreground-alt}

menu-0-0 = reboot
menu-0-0-exec = menu-open-1
menu-0-1 = power off
menu-0-1-exec = menu-open-2
menu-0-2 = suspend
menu-0-2-exec = menu-open-3
menu-0-3 = logout
menu-0-3-exec = menu-open-4

menu-1-0 = cancel
menu-1-0-exec = menu-open-0
menu-1-1 = reboot
menu-1-1-exec = systemctl reboot

menu-2-0 = power off
menu-2-0-exec = systemctl poweroff
menu-2-1 = cancel
menu-2-1-exec = menu-open-0

menu-3-0 = suspend
menu-3-0-exec = systemctl suspend
menu-3-1 = cancel
menu-3-1-exec = menu-open-0

menu-4-0 = logout
menu-4-0-exec = i3-msg exit
menu-4-1 = cancel
menu-4-1-exec = menu-open-0

[module/redshift]
type = custom/script
interval = 5

exec = ~/.config/polybar/scripts/redshift.sh

[module/music]
type = custom/script
interval = 2

label = %output:0:45:...%
exec = ~/.config/polybar/scripts/mpris.sh

[module/pavolume]
type = custom/script
tail = true
label = %output%
exec = ~/.config/polybar/scripts/pavolume.sh --listen
click-right = exec pavucontrol
click-left = ~/.config/polybar/scripts/pavolume.sh --togmute
scroll-up = ~/.config/polybar/scripts/pavolume.sh --up
scroll-down = ~/.config/polybar/scripts/pavolume.sh --down
format-background = ${colors.background}
format-foreground = ${colors.foreground}
format-underline = ${colors.primary}

; ;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

; [module/backlight]
; type = internal/xbacklight

; card = intel_backlight

; format = <ramp> <label>
; format-background = ${color.shade4}
; format-foreground = ${color.modulefg}
; format-padding = 1

; label = %percentage%%

; ramp-0 = 
; ramp-1 = 
; ramp-2 = 
; ramp-3 = 
; ramp-4 = 

; ;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/battery]
type = internal/battery

full-at = 99

battery = BAT1
adapter = ACAD

poll-interval = 2
time-format = %H:%M

format-charging = <animation-charging> <label-charging>
format-charging-background = ${colors.background}
format-charging-foreground = ${colors.foreground}
format-charging-padding = 1

format-discharging = <ramp-capacity> <label-discharging>
format-discharging-background = ${colors.background}
format-discharging-foreground = ${colors.foreground}
format-discharging-padding = 1

label-charging = %percentage%%
label-discharging = %percentage%%

label-full = Fully Charged
label-full-background = ${colors.background}
label-full-foreground = ${colors.foreground}
label-full-padding = 1

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-5 = 
ramp-capacity-6 = 
ramp-capacity-7 = 
ramp-capacity-8 = 
ramp-capacity-9 = 

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-5 = 
animation-charging-6 = 
animation-charging-7 = 
animation-charging-8 = 
animation-charging-framerate = 750

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/date]
type = internal/date
interval = 1.0
date = " %a %b %d, %Y"
date-alt = " %a %b %d, %Y"
time = %l:%M%p
time-alt = %l:%M%p
format-prefix = " "
format-background = ${colors.background}
format-foreground = ${colors.foreground}
label = "%date% %time% "
format-underline = ${colors.alert}

[module/cpu]
type = internal/cpu
interval = 1
format-prefix-foreground = ${colors.foreground-alt}
format-underline = ${colors.alert}
format-prefix = "  "

label-font = 1

; Available tags:
;   <label> (default)
;   <bar-load>
;   <ramp-load>
;   <ramp-coreload>
format = <label>


; Available tokens:
;   %percentage% (default) - total cpu load
;   %percentage-cores% - load percentage for each core
;   %percentage-core[1-9]% - load percentage for specific core
label = "Cpu %percentage:3%%"

[module/memory]
type = internal/memory
interval = 1
; Available tokens:
;   %percentage_used% 
;   %percentage_free%
;   %gb_used% (default)
;   %gb_free%
;   %gb_total%
;   %mb_used%
;   %mb_free%
;   %mb_total%
label = %gb_used%

format = "Mem <label>  "
format-prefix = "   "
format-prefix-foreground = ${colors.foreground-alt}
format-underline = ${colors.primary}

[module/networkspeedup]
type = internal/network
;interface = wlp3s0
;interface = enp14s0
;interface = enp0s31f6
interface = enp1s0
label-connected = "%upspeed:7%"
format-connected = <label-connected>
format-connected-prefix = ""
format-connected-prefix-foreground = ${colors.foreground-alt}
format-connected-foreground = ${colors.foreground}
format-connected-background = ${colors.background}
format-connected-underline = ${colors.primary}

[module/networkspeeddown]
type = internal/network
; interface = wlp3s0
; interface = enp14s0
; interface = enp0s31f6
interface = enp1s0
label-connected = "%downspeed:7%"
format-connected = <label-connected>
format-connected-prefix = ""
format-connected-prefix-foreground = ${colors.foreground-alt}
format-connected-foreground = ${colors.foreground}
format-connected-background = ${colors.background}
format-connected-underline = ${colors.alert}

[module/spotify]
type = custom/script
exec = python ~/.config/polybar/scripts/spotify.py  -f '{song} - {artist} - {album}'
interval = 1

;format = <label>
format-foreground = ${colors.foreground}
format-background = ${colors.background}

format-padding = 0
format-underline = ${colors.success}
format-prefix = "  "
format-prefix-foreground = ${colors.foreground-alt}
label = %output:0:150%

[module/pub-ip]
type = custom/script
exec = ~/.config/polybar/scripts/pub-ip.sh
interval = 100
format-foreground = ${colors.foreground}
format-background = ${colors.background}
label = %output%
format-prefix = "  "
format-prefix-foreground = ${colors.foreground}

[module/uptime]
type = custom/script
exec = uptime | awk -F, '{sub(".*up ",x,$1);print $1}'
interval = 100
label = Uptime : %output%

format-foreground = ${colors.foreground}
format-background = ${colors.background}
format-prefix = " "
format-prefix-foreground = ${colors.foreground}


[module/wireless-network]
;https://github.com/jaagr/polybar/wiki/Module:-network
type = internal/network
interface = ${env:WIRELESS}
interval = 3.0
label-connected = %essid%

format-connected = <label-connected>
;format-connected = <ramp-signal> <label-connected>
format-connected-foreground = ${colors.foreground}
format-connected-background = ${colors.background}
format-connected-prefix = "  "
format-connected-prefix-foreground = #7e52c6
format-connected-prefix-background = ${colors.background}
format-connected-underline = #7e52c6

label-disconnected = %ifname% disconnected
label-disconnected-foreground = ${colors.alert}
label-disconnected-background = ${colors.background}

format-disconnected = <label-disconnected>
format-disconnected-foreground = ${colors.alert}
format-disconnected-background = ${colors.background}
format-disconnected-prefix = "  "
format-disconnected-prefix-foreground = ${colors.alert}
format-disconnected-prefix-background = ${colors.background}
format-disconnected-underline =${colors.alert}

ramp-signal-0 = ▁
ramp-signal-1 = ▂
ramp-signal-2 = ▃
ramp-signal-3 = ▄
ramp-signal-4 = ▅
ramp-signal-5 = ▆
ramp-signal-6 = ▇
ramp-signal-7 = █
ramp-signal-foreground = #7e52c6


[module/bspwm]
type = internal/bspwm
pin-workspaces = false
inline-mode = false
enable-click = true
enable-scroll = false
reverse-scroll = false
fuzzy-match = true

ws-icon-[0-9]+ = <label>;<icon>
; Note that the <label> needs to correspond with the bspwm workspace name
; Neither <label> nor <icon> can contain a semicolon (;)
ws-icon-0 = 1; 
ws-icon-1 = 2;
ws-icon-2 = 3;
ws-icon-3 = 4;
ws-icon-4 = 5;
ws-icon-5 = 6;
ws-icon-6 = 7;
ws-icon-7 = 8;
ws-icon-8 = 9;
ws-icon-9 = 0;
ws-icon-default =""

; Available tags:
;   <label-monitor>
;   <label-state> - gets replaced with <label-(focused|urgent|occupied|empty)>
;   <label-mode> - gets replaced with <label-(monocle|tiled|fullscreen|floating|locked|sticky|private)>
; Default: <label-state>
format = <label-state> <label-mode>

label-monitor = %name%

label-dimmed-foreground = ${colors.foreground}
label-dimmed-focused-background = ${colors.background-alt}

label-focused = %icon%
label-focused-background = ${colors.background-alt}
label-focused-underline= ${colors.primary}
label-focused-padding = 2


label-occupied = %icon%
label-occupied-background = ${colors.background}
label-occupied-foreground= ${colors.foreground}
label-occupied-padding = 2
label-occupied-underline= ${colors.alert}


label-urgent = %icon%
label-urgent-foreground = ${colors.foreground}
label-urgent-background = ${colors.background}

label-empty = %icon%
label-empty-foreground = ${colors.foreground}
label-empty-background = ${colors.background}
label-empty-padding = 2

[module/ewmh]
type = internal/xworkspaces

pin-workspaces = false
enable-click = true
enable-scroll = true
reverse-scroll = true


icon-0 = 1;
icon-1 = 2;
icon-2 = 3;
icon-3 = 4;
icon-4 = 5;
#icon-5 = 6;
format = <label-state>
label-monitor = %name%

label-active = %name%
label-active-foreground = ${colors.foreground}
label-active-background = ${colors.background}
label-active-underline= #6790eb
label-active-padding = 2

label-occupied = %name%
label-occupied-background = ${colors.background}
label-occupied-padding = 2

label-urgent = %name%
label-urgent-foreground = ${colors.foreground}
label-urgent-background = ${colors.alert}
label-urgent-underline = ${colors.alert}
label-urgent-padding = 2


label-empty = %name%
label-empty-foreground = ${colors.foreground}
label-empty-padding = 2
format-foreground = ${colors.foreground}
format-background = ${colors.background}