[colors]
;background = ${xrdb:color0:#222}
;foreground = ${xrdb:color7:#222}
background = none
background-alt = #5c6370
foreground = #c5c8c6
foreground-alt = #c5c8c6
primary = #2257A0
secondary = #d19a66
alert = #e06c75
success = #dd8844
color9 = #ECBE7B

